#!/usr/bin/env python3
"""build_preview.py — Render what index.html would look like if collection resumed.

    python analysis/build_preview.py
    cd private/preview && python -m http.server 8777      # then open :8777

Writes private/preview/. That directory is gitignored, is not in the workflow's
`git add` list, and is not assembled into ./dist by the Cloudflare build — so
this page cannot reach findstorage.pages.dev by any path. **The published
index.html is never modified by this script.**

WHY THIS EXISTS
---------------
index.html is hand-maintained. Nothing regenerates it, and it is not in the
commit list, so when the daily workflow runs it refreshes every page *except*
the front one. The landing page would go on saying collection ended on
25 August 2026 while the pages behind it showed current numbers.

This renders the alternative without committing to it, so the decision about
what the front page should say can be made by looking at the thing rather than
imagining it.

FAILS LOUDLY BY DESIGN
----------------------
Every substitution below asserts that its target was actually found. If
index.html is edited and a replacement silently matches nothing, the preview
would quietly show stale sunset copy while claiming to be the live version —
which is the exact failure this script exists to make visible. It refuses
instead.
"""
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(".")
SRC = ROOT / "index.html"
OUTDIR = ROOT / "private" / "preview"

# Files index.html fetches at runtime, per the note in wrangler.jsonc.
# locations.json is a FALLBACK, not a second source: index.html:374 loops
# ['enriched_locations.json', 'locations.json'] and returns on the first that
# loads. Its absence is normal and is not a defect, so it is not reported as
# one — a warning that fires on every healthy run teaches you to ignore
# warnings.
DATA_FILES = ["enriched_locations.json", "store-history.json",
              "markets-detail.json"]
OPTIONAL = ["locations.json"]

BANNER = """
<!-- PREVIEW BUILD — not the published site. Generated by
     analysis/build_preview.py into private/, which is gitignored and is not
     copied into ./dist. -->
<div style="position:sticky;top:0;z-index:99999;background:#7a2e0e;color:#fff;
            font:600 13px/1.5 system-ui,sans-serif;padding:9px 14px;
            letter-spacing:.02em;text-align:center">
  PREVIEW BUILD — local only, never published. This is what the front page
  would look like if collection resumed. The live site is unchanged.
</div>
"""


def latest_collection_date():
    """Most recent date present in the daily store history."""
    dates = []
    for p in sorted((ROOT / "history").glob("20*.csv")):
        if re.fullmatch(r"20\d\d-\d\d", p.stem):
            with open(p, newline="", encoding="utf-8", errors="replace") as f:
                next(f, None)
                for line in f:
                    d = line.split(",", 1)[0].strip()
                    if re.fullmatch(r"20\d\d-\d\d-\d\d", d):
                        dates.append(d)
    return max(dates) if dates else None


def pretty(iso):
    y, m, d = iso.split("-")
    months = ("January February March April May June July August September "
              "October November December").split()
    return f"{int(d)} {months[int(m) - 1]} {y}"


def sub_once(html, pattern, repl, label, flags=0):
    new, n = re.subn(pattern, repl, html, flags=flags)
    if n == 0:
        sys.exit(f"REFUSING: '{label}' matched nothing in {SRC}.\n"
                 f"  index.html has changed and this script would have produced "
                 f"a preview still carrying the old copy. Fix the pattern, then "
                 f"re-run. Nothing was written.")
    print(f"  {label}: {n} replacement(s)")
    return new


def main():
    if not SRC.exists():
        sys.exit(f"{SRC} not found — run from the repo root.")

    latest = latest_collection_date()
    if not latest:
        sys.exit("No dated rows found in history/ — cannot date the preview.")
    stores = len(json.loads((ROOT / "enriched_locations.json")
                            .read_text(encoding="utf-8")))
    print(f"latest collection date in history/: {latest}")
    print(f"stores in enriched_locations.json: {stores:,}\n")

    html = SRC.read_text(encoding="utf-8")

    # 1. Drop the discontinued modal. Both JS touch points null-guard with
    #    `if (el)`, so removing the element cannot throw.
    html = sub_once(
        html,
        r'<div class="notice-overlay" id="notice-overlay".*?</div>\s*</div>',
        '<!-- discontinued notice removed in the preview build -->',
        "discontinued modal removed", flags=re.S)

    # 2. Hero copy — store count and the "final collection date" clause.
    html = sub_once(
        html,
        r'([\d,]+) U\.S\. self-storage locations',
        f'{stores:,} U.S. self-storage locations',
        "hero store count")
    html = sub_once(
        html,
        r'Unit pricing as advertised on [^.]+, the final collection date\.',
        f'Unit pricing as advertised on {pretty(latest)}.',
        "hero collection-date clause")

    # 3. Per-store chart empty state.
    html = sub_once(
        html,
        r"No price history was logged for this store '\s*\+\s*"
        r"'before collection ended on [^.']+\.",
        "No price history has been logged for this store yet.",
        "price-history empty state")

    # 4. Unmissable preview banner.
    html = sub_once(html, r"<body>", "<body>\n" + BANNER, "preview banner")

    OUTDIR.mkdir(parents=True, exist_ok=True)
    (OUTDIR / "index.html").write_text(html, encoding="utf-8")

    copied, missing = [], []
    for name in DATA_FILES + OPTIONAL:
        src = ROOT / name
        if src.exists():
            shutil.copy2(src, OUTDIR / name)
            copied.append(f"{name} ({src.stat().st_size / 1e6:.1f} MB)")
        elif name in DATA_FILES:
            missing.append(name)

    print(f"\nwrote {OUTDIR / 'index.html'}")
    for c in copied:
        print(f"  copied {c}")
    for m in missing:
        print(f"  NOT FOUND (page may not fully render): {m}")

    print(f"\nserve it — file:// will not work, the page fetches JSON:\n"
          f"  cd {OUTDIR} && python -m http.server 8777\n"
          f"  then open http://localhost:8777\n")
    print("The published index.html was not touched.")


if __name__ == "__main__":
    main()
